name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Injeta a chave no HTML (substitui o placeholder)
      - name: Inject GROQ key
        run: |
          sed -i 's/__GROQ_API_KEY__/'"${{ secrets.GROQ_API_KEY }}"'/g' index.html

      # Publica os arquivos como artefato pro Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
